### ISSUE TITLE
Does not support org-refile or subtasks

### ISSUE THREAD

**Issue by atanasj** [ginqi7/org-reminders#16]
This below features seem to be missing

- [ ] `org-refile`: this would benefit moving tasks between 'lists' / headings
- [ ] subtasks: this is available via 'indentation' feature in the Reminders.app

Not sure if either of these features are possible, but they certainly would be helpful.

**Comment by ginqi7** [comment]
Thank you for your suggestion.

I will check if they can be implemented using the Apple Swift API.

I believe the `org-refile` can be implemented, but the `subtasks` currently have no ideas on how to proceed.

**Comment by ginqi7** [comment]
I have implemented `org-refile` in the latest version.

Please upgrade `org-reminders-cli` to version 0.0.7.

```
brew install org-reminders-cli
```
```
==> Upgrading ginqi7/formulae/org-reminders-cli
  0.0.6 -> 0.0.7
🍺  /opt/homebrew/Cellar/org-reminders-cli/0.0.7: 4 files, 7.2MB, built in 1 second
```

**Comment by atanasj** [comment]
Using the latest version, this does not seem to be working:

https://github.com/user-attachments/assets/ac42f308-0fb6-4d56-a2c0-d4994e899b2e

**Comment by ginqi7** [comment]
@atanasj 
Does editing an existing to-do item sync to Reminders?

Could you post the details of the todo properties? I suspect the LAST-MODIFIED  property does not match your system time.

**Comment by atanasj** [comment]
When `org-reminders` is working as expected, yes, it does sync. However, this is more about the refile. Is that related?

**Comment by atanasj** [comment]
I've moved to a dir with no sync, and still the same issue (2). However, not sure how to resolve 1. What can I do on my end? The time stamp is automatic, and it seems to match my system time.

**Comment by ginqi7** [comment]
Please send me the log for this situation so I can review the sync steps.

**Comment by atanasj** [comment]
```
WebSocket Client org-reminders connected, the server port is 53445
Variable [org-reminders-sync-file] is /Users/atanas/git/reminders.org in Emacs.
Variable [org-reminders-display-options] is incomplete in Emacs.
Variable [org-reminders-sync-frequency] is Optional(1) in Emacs.
(org-reminders-message-handle "204E52A0-BD36-4150-BD24-8BF6E0FA9532" "Update" "CommonReminder" "ewogICJoYXNoIiA6ICJmYjliMmNmZTdlMjgyZmMyMDdiNzIwZmM3ZDg0NDVlMzdjMTBmMDZiMmJhYjM3MThiZmFhMmZhY2M1OTc1YmQxIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNToxOCIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI2NjQ3RUM3Qy01RjAwLTQ2RDgtQjBBMi0wMEFFODIzM0UxRDciLAogICAgInRpdGxlIiA6ICJMaXN0IDMiCiAgfSwKICAicHJpb3JpdHkiIDogMCwKICAidGl0bGUiIDogInR3ZW50eSB0aHJlZSBib3R0bGVzIgp9")
(org-reminders-message-handle "FA4D3E61-F4BC-494F-8785-494DEEC04C92" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "C9A3209A-0388-4B23-BEE2-C3F3B3D80016" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "FDEE7EC5-9B87-4A60-8B9F-317D89C9D56D" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI5NDQxRkJFNC1BOEYxLTQ1NEItODlFMy0zRTZFRTk4N0U2MDQiLAogICJoYXNoIiA6ICJmYjliMmNmZTdlMjgyZmMyMDdiNzIwZmM3ZDg0NDVlMzdjMTBmMDZiMmJhYjM3MThiZmFhMmZhY2M1OTc1YmQxIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNToxOSIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI2NjQ3RUM3Qy01RjAwLTQ2RDgtQjBBMi0wMEFFODIzM0UxRDciLAogICAgInRpdGxlIiA6ICJMaXN0IDMiCiAgfSwKICAicHJpb3JpdHkiIDogMCwKICAidGl0bGUiIDogInR3ZW50eSB0aHJlZSBib3R0bGVzIgp9")
(org-reminders-message-handle "7C5268CB-17FF-4D4F-A8E2-14350BAC8A73" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "242FEA2C-9207-45CF-85B6-E8FA9782EF59" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "57A2B4C8-9356-48E0-8375-3CF93EF4CBB0" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI5NDQxRkJFNC1BOEYxLTQ1NEItODlFMy0zRTZFRTk4N0U2MDQiLAogICJoYXNoIiA6ICIyYTk5MzUwZWRkYjUwMjUwOTBjMzlkMjliMDM2NGIyOTdmZDcxZWE4MmFkZWI1MWEwZTk4ZTg4OWZmZTAwOWQ5IiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNTozMiIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI2NjQ3RUM3Qy01RjAwLTQ2RDgtQjBBMi0wMEFFODIzM0UxRDciLAogICAgInRpdGxlIiA6ICJMaXN0IDMiCiAgfSwKICAibm90ZXMiIDogIlRoaXMgaXMgYSB0cmVlIG1hZGUgb2YgYm90dGxlcyIsCiAgInByaW9yaXR5IiA6IDAsCiAgInRpdGxlIiA6ICJ0d2VudHkgdGhyZWUgYm90dGxlcyIKfQ==")
(org-reminders-message-handle "E2CCAA53-4EA2-4582-BC30-56D7E9C362DA" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "3DA083E2-3245-4DA7-9EC9-110D7DC22597" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "D6B9624E-44E0-4781-8C14-EFCF63E2CD39" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI5NDQxRkJFNC1BOEYxLTQ1NEItODlFMy0zRTZFRTk4N0U2MDQiLAogICJoYXNoIiA6ICIyYTk5MzUwZWRkYjUwMjUwOTBjMzlkMjliMDM2NGIyOTdmZDcxZWE4MmFkZWI1MWEwZTk4ZTg4OWZmZTAwOWQ5IiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNTozMyIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI2NjQ3RUM3Qy01RjAwLTQ2RDgtQjBBMi0wMEFFODIzM0UxRDciLAogICAgInRpdGxlIiA6ICJMaXN0IDMiCiAgfSwKICAibm90ZXMiIDogIlRoaXMgaXMgYSB0cmVlIG1hZGUgb2YgYm90dGxlcyIsCiAgInByaW9yaXR5IiA6IDAsCiAgInRpdGxlIiA6ICJ0d2VudHkgdGhyZWUgYm90dGxlcyIKfQ==")
(org-reminders-message-handle "59AEBB0B-6C86-4A9A-BC22-E909F0CA41F3" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "BFD16933-B81B-4497-82AA-5D541F4BC749" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "C9CFD472-8769-4419-A079-5D1B81BE3686" "Update" "CommonReminder" "ewogICJoYXNoIiA6ICI1Y2M4NzQwODE1ZDg3ZjZjMmM5NmJlNzkzMDAwZjRmMTg3ZTU2NTAxY2FjM2NkN2EyZjVhZmFjNWQzNmJhZDJlIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNTo1MSIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI2NjQ3RUM3Qy01RjAwLTQ2RDgtQjBBMi0wMEFFODIzM0UxRDciLAogICAgInRpdGxlIiA6ICJMaXN0IDMiCiAgfSwKICAibm90ZXMiIDogIkdvLCB0aGVuLCBkbyB0aGUgc2FtZS4iLAogICJwcmlvcml0eSIgOiAwLAogICJ0aXRsZSIgOiAiZ28gYWdhaW4gYW5kIGRvIHRoZSBzYW1lIgp9")
(org-reminders-message-handle "760B603D-8059-4492-983B-260BA9FE5F9E" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "4755716C-A4F6-4B83-80BF-B5F7BCBA3930" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "3EB365E7-A896-418A-AEC8-9526395F7FED" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICIyQTE0RDAzMy1CNzRCLTQ0NEYtODBCOC1DNTdCODM4NkQzNzQiLAogICJoYXNoIiA6ICI1Y2M4NzQwODE1ZDg3ZjZjMmM5NmJlNzkzMDAwZjRmMTg3ZTU2NTAxY2FjM2NkN2EyZjVhZmFjNWQzNmJhZDJlIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNTo1MiIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI2NjQ3RUM3Qy01RjAwLTQ2RDgtQjBBMi0wMEFFODIzM0UxRDciLAogICAgInRpdGxlIiA6ICJMaXN0IDMiCiAgfSwKICAibm90ZXMiIDogIkdvLCB0aGVuLCBkbyB0aGUgc2FtZS4iLAogICJwcmlvcml0eSIgOiAwLAogICJ0aXRsZSIgOiAiZ28gYWdhaW4gYW5kIGRvIHRoZSBzYW1lIgp9")
(org-reminders-message-handle "3572744E-A3F4-4C90-9BA1-74CC41FEE906" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "D094585C-DCA5-46B8-A6F4-DC2264DA52F9" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "93E03AF4-E6A7-483E-A5E0-900D1C55797B" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "9C1DF5DF-43DB-4657-9976-5A99C2A9A5A0" "Update" "CommonList" "ewogICJpZCIgOiAiQzNFNjc1NDgtMERGQi00NTdCLUJFOTEtRUNBQkNGOTEzOTAwIiwKICAidGl0bGUiIDogIkxpc3QgNCIKfQ==")
(org-reminders-message-handle "388F7ADD-36D2-41FC-B231-C2F39E4B8A4F" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "BB0365D4-36EB-41D0-87EF-91138678539E" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "21224B7E-F508-433C-B889-D822DF9DA7EA" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "96A5C92D-2ED3-4D19-A878-0D48527A153C" "Update" "CommonReminder" "ewogICJoYXNoIiA6ICI4NTkxMWViZGFhOWIyNmI4YzE3NzgyMTI0OTc4OGJjM2Q5OTk4MjhmNzU5ZmI4MDMwMmVjYjRkMjM0OWNkNTRkIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNjoyNSIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICJDM0U2NzU0OC0wREZCLTQ1N0ItQkU5MS1FQ0FCQ0Y5MTM5MDAiLAogICAgInRpdGxlIiA6ICJMaXN0IDQiCiAgfSwKICAicHJpb3JpdHkiIDogMCwKICAidGl0bGUiIDogIml0ZW1zIGFyZSBuaWNlIgp9")
(org-reminders-message-handle "98E7A29F-C526-4A8A-B9A4-36BE19107F6B" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "4C35FC96-2832-4E46-9B79-D1723619A518" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "07BB6C01-67FD-4B6E-B484-14DD727FD0C9" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI2M0UyMkU3Qi0yODQwLTQ4MDYtOEY4Qy01NDc0MjQwQzVENEEiLAogICJoYXNoIiA6ICI4NTkxMWViZGFhOWIyNmI4YzE3NzgyMTI0OTc4OGJjM2Q5OTk4MjhmNzU5ZmI4MDMwMmVjYjRkMjM0OWNkNTRkIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNjoyNiIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICJDM0U2NzU0OC0wREZCLTQ1N0ItQkU5MS1FQ0FCQ0Y5MTM5MDAiLAogICAgInRpdGxlIiA6ICJMaXN0IDQiCiAgfSwKICAicHJpb3JpdHkiIDogMCwKICAidGl0bGUiIDogIml0ZW1zIGFyZSBuaWNlIgp9")
(org-reminders-message-handle "99C14E4C-FD6C-4339-9FF7-02389DA9D23A" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "0D6C7052-43D0-46E5-A7E8-B25D3F6189C0" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "F2B65E43-5D77-43DB-8C7B-028B975B005D" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI2M0UyMkU3Qi0yODQwLTQ4MDYtOEY4Qy01NDc0MjQwQzVENEEiLAogICJoYXNoIiA6ICI5MDBkZmY2NWI1OTg1NjUzMjc1N2MzMTJhZTg2MTNmZmFmNTRmZmE0ZDA0ZjBlNDMzY2MwY2FiNDg3NzcxOTY4IiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNjozNSIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICJDM0U2NzU0OC0wREZCLTQ1N0ItQkU5MS1FQ0FCQ0Y5MTM5MDAiLAogICAgInRpdGxlIiA6ICJMaXN0IDQiCiAgfSwKICAibm90ZXMiIDogIlRoaXMgaXMgYSB0ZXN0IGl0ZW0iLAogICJwcmlvcml0eSIgOiAwLAogICJ0aXRsZSIgOiAiaXRlbXMgYXJlIG5pY2UiCn0=")
(org-reminders-message-handle "735A67BB-C580-4AE6-B837-E920D133B9A4" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "19BB1AC4-D6E2-4F01-AF2E-B9989046738D" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "423296FD-F8BA-46CD-BA48-1C4BAA74C4E4" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI2M0UyMkU3Qi0yODQwLTQ4MDYtOEY4Qy01NDc0MjQwQzVENEEiLAogICJoYXNoIiA6ICI5MDBkZmY2NWI1OTg1NjUzMjc1N2MzMTJhZTg2MTNmZmFmNTRmZmE0ZDA0ZjBlNDMzY2MwY2FiNDg3NzcxOTY4IiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNjozNiIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICJDM0U2NzU0OC0wREZCLTQ1N0ItQkU5MS1FQ0FCQ0Y5MTM5MDAiLAogICAgInRpdGxlIiA6ICJMaXN0IDQiCiAgfSwKICAibm90ZXMiIDogIlRoaXMgaXMgYSB0ZXN0IGl0ZW0iLAogICJwcmlvcml0eSIgOiAwLAogICJ0aXRsZSIgOiAiaXRlbXMgYXJlIG5pY2UiCn0=")
(org-reminders-message-handle "920ADB03-91A8-4167-B6BF-6AD8823C9904" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "FC629623-9AE0-4A1B-B8D4-A6830BB90E58" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "20EA33A8-376F-4BC2-9C6B-C42687092DE4" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "3D526D38-26E4-490B-891B-141D543D7A77" "Update" "CommonList" "ewogICJpZCIgOiAiNEIyQUFBQ0MtRUQxMC00RUJFLThGNkQtRDkxNTkyMDYxNzg2IiwKICAidGl0bGUiIDogIkxpc3QgNSIKfQ==")
(org-reminders-message-handle "DF37BAA3-2313-47FF-95FE-76CB0AE63A87" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "C9932346-D979-4DB7-B987-B859E1F1724F" "Update" "CommonList" "ewogICJpZCIgOiAiRjA2NUQ3MEItNTkyOC00QThFLTkxQjktRjgwRDVBOUFCMDgyIiwKICAidGl0bGUiIDogIkxpc3QgNiIKfQ==")
(org-reminders-message-handle "1D897813-1FF7-4A71-A409-3E3085B184F0" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "B6CCD5F8-5632-447B-80CE-4D3E118E065E" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "CAD328E7-153A-4942-B087-8C201A12C306" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "617DD10A-3F91-45EB-81DE-A8FFDF2CF5C1" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "8309F549-1675-4A43-9849-A0030185CC2D" "Update" "CommonReminder" "ewogICJoYXNoIiA6ICJkOWIzNDM5MTExN2U0YWU2NDU1MTU5Nzc1NmNhYjAwOWY0OWFmOTBiOGU5YTc2MTk3MzEzNTlmMTQ0NjdhNDE3IiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNzowNiIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI0QjJBQUFDQy1FRDEwLTRFQkUtOEY2RC1EOTE1OTIwNjE3ODYiLAogICAgInRpdGxlIiA6ICJMaXN0IDUiCiAgfSwKICAibm90ZXMiIDogIlRoaXMgaXMgcmVhbGx5IG5pY2U/IiwKICAicHJpb3JpdHkiIDogMCwKICAidGl0bGUiIDogInRoaXMgaXMgbmljZSB0b28iCn0=")
(org-reminders-message-handle "9DDE2A81-712A-4896-A9D0-BC84EB4DA2CF" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "D56CFF99-7558-47D1-94DE-D8B953D90CA8" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "63F2BE06-39F6-4D15-8FFF-A8CEFDA7212C" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI5NjE1MTExNC1DODhCLTQzNDItOTkyRi0zQjA1NkZGNDY0NEUiLAogICJoYXNoIiA6ICJkOWIzNDM5MTExN2U0YWU2NDU1MTU5Nzc1NmNhYjAwOWY0OWFmOTBiOGU5YTc2MTk3MzEzNTlmMTQ0NjdhNDE3IiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNzowNiIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI0QjJBQUFDQy1FRDEwLTRFQkUtOEY2RC1EOTE1OTIwNjE3ODYiLAogICAgInRpdGxlIiA6ICJMaXN0IDUiCiAgfSwKICAibm90ZXMiIDogIlRoaXMgaXMgcmVhbGx5IG5pY2U/IiwKICAicHJpb3JpdHkiIDogMCwKICAidGl0bGUiIDogInRoaXMgaXMgbmljZSB0b28iCn0=")
(org-reminders-message-handle "6A3A3C41-87D4-4ED9-A1E7-508B3126C387" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "1C13B52A-07AB-4755-8447-7CDE827D3D8A" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "62A013F3-C5FC-4166-A806-105D9158A9E1" "Update" "CommonReminder" "ewogICJoYXNoIiA6ICIxZDFkZTNiZjg2YzBhYzgxMTk0YzY0OTMwMjA4MzdiNzg3ZWVhZjgyM2JlZDlhNTdmYmFkNzNlNGQxMjgzYzUxIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNzo0NCIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICJGMDY1RDcwQi01OTI4LTRBOEUtOTFCOS1GODBENUE5QUIwODIiLAogICAgInRpdGxlIiA6ICJMaXN0IDYiCiAgfSwKICAibm90ZXMiIDogIkdldCBpbiB0aGVyZSIsCiAgInByaW9yaXR5IiA6IDAsCiAgInRpdGxlIiA6ICJnZXQgaW4gdGhlcmUsIGJybyIKfQ==")
(org-reminders-message-handle "5C324BDA-A479-4448-86B5-E4B1DA08D019" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "37D79D9C-1B2F-428E-866D-D8FA5C441465" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "CE24C9B8-B4AD-4645-B330-F3FF92AC3174" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI3NEM3Q0I3NS0wRjM0LTRERjEtQTI5RC1GNUQzNTk3QUEwQzUiLAogICJoYXNoIiA6ICIxZDFkZTNiZjg2YzBhYzgxMTk0YzY0OTMwMjA4MzdiNzg3ZWVhZjgyM2JlZDlhNTdmYmFkNzNlNGQxMjgzYzUxIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNzo0NSIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICJGMDY1RDcwQi01OTI4LTRBOEUtOTFCOS1GODBENUE5QUIwODIiLAogICAgInRpdGxlIiA6ICJMaXN0IDYiCiAgfSwKICAibm90ZXMiIDogIkdldCBpbiB0aGVyZSIsCiAgInByaW9yaXR5IiA6IDAsCiAgInRpdGxlIiA6ICJnZXQgaW4gdGhlcmUsIGJybyIKfQ==")
(org-reminders-message-handle "D2726B12-2EC3-4CE6-BB02-F4469DA85B27" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "5DC025B6-D604-4E97-8CAD-3354484FF556" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "635A33D9-B96E-4A67-A8AA-5E2ADB6ABE92" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "D8FF3BCC-506D-41D4-9271-06805C64EA67" "Delete" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI3NEM3Q0I3NS0wRjM0LTRERjEtQTI5RC1GNUQzNTk3QUEwQzUiLAogICJoYXNoIiA6ICIxZDFkZTNiZjg2YzBhYzgxMTk0YzY0OTMwMjA4MzdiNzg3ZWVhZjgyM2JlZDlhNTdmYmFkNzNlNGQxMjgzYzUxIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNzo0NSIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI0QjJBQUFDQy1FRDEwLTRFQkUtOEY2RC1EOTE1OTIwNjE3ODYiLAogICAgInRpdGxlIiA6ICJMaXN0IDUiCiAgfSwKICAibm90ZXMiIDogIkdldCBpbiB0aGVyZSIsCiAgInByaW9yaXR5IiA6IDAsCiAgInRpdGxlIiA6ICJnZXQgaW4gdGhlcmUsIGJybyIKfQ==")
(org-reminders-message-handle "B718053B-EE72-4AB4-BBFE-9B3D5C0102FC" "Update" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI3NEM3Q0I3NS0wRjM0LTRERjEtQTI5RC1GNUQzNTk3QUEwQzUiLAogICJoYXNoIiA6ICI0ZDU5MTIwMWU2Y2NjZDM1MWY4MWRmZWRkMWJlNmQ2MzNhOGNiNDVlM2U0Y2Q3Zjc2MzFiNWQ5ZmQzMmVkY2ExIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowODowMiIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICI0QjJBQUFDQy1FRDEwLTRFQkUtOEY2RC1EOTE1OTIwNjE3ODYiLAogICAgInRpdGxlIiA6ICJMaXN0IDUiCiAgfSwKICAibm90ZXMiIDogIkdldCBpbiB0aGVyZSIsCiAgInByaW9yaXR5IiA6IDAsCiAgInRpdGxlIiA6ICJnZXQgaW4gdGhlcmUsIGJybyIKfQ==")
(org-reminders-message-handle "E6619A76-7EC0-4813-B189-C337CC8EC54D" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "E7134C14-53DC-437B-98FE-57D7718B6ACB" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
(org-reminders-message-handle "D0D0B2E7-1C4D-4D41-A0C9-F02D096BBD01" "Add" "CommonReminder" "ewogICJleHRlcm5hbElkIiA6ICI3NEM3Q0I3NS0wRjM0LTRERjEtQTI5RC1GNUQzNTk3QUEwQzUiLAogICJoYXNoIiA6ICIxZDFkZTNiZjg2YzBhYzgxMTk0YzY0OTMwMjA4MzdiNzg3ZWVhZjgyM2JlZDlhNTdmYmFkNzNlNGQxMjgzYzUxIiwKICAiaXNDb21wbGV0ZWQiIDogZmFsc2UsCiAgImxhc3RNb2RpZmllZCIgOiAiMjAyNS0wNC0xMSAwODowNzo0NSIsCiAgImxpc3QiIDogewogICAgImlkIiA6ICJGMDY1RDcwQi01OTI4LTRBOEUtOTFCOS1GODBENUE5QUIwODIiLAogICAgInRpdGxlIiA6ICJMaXN0IDYiCiAgfSwKICAibm90ZXMiIDogIkdldCBpbiB0aGVyZSIsCiAgInByaW9yaXR5IiA6IDAsCiAgInRpdGxlIiA6ICJnZXQgaW4gdGhlcmUsIGJybyIKfQ==")
(org-reminders-message-handle "F2B9128D-48F6-4F82-BC93-91324BFBCECD" "Sync" "CommonList" "ewogICJpZCIgOiAiMCIsCiAgInRpdGxlIiA6ICIwIgp9")
```

**Comment by ginqi7** [comment]
I have no idea about your problem at the moment. You could try upgrading to the latest version. I hope it resolves the issue.

**Comment by ginqi7** [comment]
if you manually cut a task into another headline in an org mode file, will it sync to Reminders?

**Comment by atanasj** [comment]
Yes, it does. This seems to work fine, just not the refile.

**Comment by ginqi7** [comment]
It appears that `refile` isn't simply a cut-and-paste operation. I'll examine the `org-refile` code to identify the issue. What version of org mode are you using?

**Comment by atanasj** [comment]
Not sure, I'm on Emacs 29.1

**Comment by ginqi7** [comment]
I tested org mode version 9.6 with Emacs -Q, and the org-refile function works fine.

Maybe you could test it with Emacs -Q; perhaps some other package is interfering with org-reminders.

I recommend using this tool [emacsq-sh](https://github.com/twlz0ne/emacsq-sh) to test packages like Emacs -Q.

**Comment by atanasj** [comment]
When I test it with `emacs -Q` and call the file, it does not load any additional packages, e.g., `org-reminders` or the `websocket-bridge`, as when I call them, they are not active. I believe `org-mode` and therefore `org-refile` is a default package. `org-refile` works, but does not update the items in the Reminders.app.

**Comment by ginqi7** [comment]
I mean to open Emacs with the `emacs -Q` command, load the `websocket`, `org-reminders`, and `websocket-bridge` packages, and then test the functions of `org-reminders` to exclude any interference from other packages.

You can use https://github.com/twlz0ne/emacsq-sh to simplify the testing process.
```
emacsq-sh -L {your-websocket-path} -L {your-websocket-bridge-path} -L {your-org-reminders-path} -P org-reminders.
```
It will simply load org-reminders in your Emacs, allowing you to test everything you desire.

**Comment by atanasj** [comment]
I cannot load the packages when running `emacs -Q`... Not sure if this is related to using straight package manager.

**Comment by ginqi7** [comment]
> I cannot load the packages when running `emacs -Q`... Not sure if this is related to using straight package manager.

`Emacs -Q` means loading no external packages, so you need to manually add the load path and require the necessary packages.

**Comment by atanasj** [comment]
Okay, I can confirm it works with the `emacs -Q` above. I need to figure out what is getting in the way.

**Comment by atanasj** [comment]
It seems that when I disable the `websocket-bridge` package, refile works, and then when restarting the sync process, the item is moved. Could there be some conflict with `websocket-bridge` and `org-refile`?

**Comment by ginqi7** [comment]
The `websocket-bridge` solely facilitates communication between Emacs and Swift program.

**Comment by atanasj** [comment]
Okay. As an aside, and not sure how / if it is related, but `org-refile` to another org file works okay, as it copies to the new org file, but the items reappears in the original `org-reminders` org buffer. If I remove the properties from the item, it copies to a new list in the `org-reminders` org buffer, but then replaces the same item back to the original list, but now with tow different hashes ids.

```org

* list 1 [0/4]
:PROPERTIES:
:LIST-ID: 92624B54-6B2A-4582-BB85-914E4587FAE9
:END:

...

** TODO test
:PROPERTIES:
:HASH:     3e88d4d6f61b41b5098eec4247412521d1de058f45a767e346a1eea69b3a973e
:LAST-MODIFIED: 2025-04-15 12:16:54
:EXTERNAL-ID: D7A678F0-80E7-4AD1-8F03-D536A053A613
:END:
test this
 
* list 2 [0/2]
:PROPERTIES:
:LIST-ID:  D07742BA-18FF-49C5-BB26-B9158827A6CD
:END:

...

** TODO test
:PROPERTIES:
:HASH:     6cbb81c53a2f9baa57344f57488b47ba2f37052c8cd946643e2c9b818ab89ca4
:LAST-MODIFIED: 2025-04-15 12:15:18
:EXTERNAL-ID: E7167A7E-93F9-4AAF-8876-A4CEBE6735FC
:END:
test this
```

Any thoughts... Do I still need to look elsewhere for a solution...

**Comment by ginqi7** [comment]
This behavior is expected because deleting an item in the org mode file does not remove the corresponding item in Reminders.

If you delete an org item, org-reminders will **recover** it from Reminders. If you delete the EXTERNAL-ID propertie of an item, `org-reminders` will interpret this as the **addition** of a new item with the same title.

`org-refile` or moving an item to another headline means that `org-reminders` considers the item **updated**.

**Comment by atanasj** [comment]
`org-refile` is working, it was a configuration issue in `doomemacs`.  For those stumbling upon this issue, below is the config I used:

```elisp
(use-package! org-reminders
  :init
  (setq org-reminders-sync-file (expand-file-name "reminders.org" org-directory))
  :config
  (websocket-bridge-server-start)
  (setq org-reminders-display-options "incomplete")
  (org-reminders-start-auto-sync)
  ;; (setq org-after-refile-insert-hook nil)
  )

(defun save-after-websocket-and-refile ()
  "Save the buffer after websocket-bridge has completed its work when using refile."
  (if (and (boundp 'org-reminders-sync-file)
           (string= (buffer-file-name) org-reminders-sync-file))
      ;; Special handling for org-reminders files
      (if (bound-and-true-p websocket-bridge-server)
          ;; If websocket-bridge is active, save after it completes
          (websocket-bridge-after-work #'save-buffer)
        ;; Otherwise, save immediately
        (save-buffer))
    ;; Default save behavior for other files
    (save-buffer)))

(defun websocket-bridge-after-work (callback)
  "Execute CALLBACK after websocket-bridge has finished its work."
  ;; Replace this simulation with actual logic to determine when WebSocket processing is complete
  (run-at-time 1 nil callback))

(defun setup-save-hook-for-refile ()
  "Set up the saving logic for org refiling."
  (setq org-after-refile-insert-hook
        '(save-after-websocket-and-refile)))

;; Ensure the setup function is called
(setup-save-hook-for-refile)

```

**Comment by ginqi7** [comment]
Thank you for your efforts.

To summarize, your previous problem was caused by the `org-after-refile-insert-hook`:

1. The documentation on `org-after-refile-insert-hook` states that the hook is run **before** the contents of the **old** location are remove.
2. the `org-reile` process should be:
   - copy headline to a new positon
   - run `org-after-refile-insert-hook`
   - remove the contents of the old postion.
3. When you run `org-refile`, Emacs will copy the todo item to a new position.
4.  if the hook saves the buffer, there will be two identical to-do items in the buffer, and **org-reminders will delete the latter**.
5. When the hook is complete, `org-refile` will delete the contents of the old location and **the buffer will lose the todo item**.
6. org-reminders copies a new reminder from MacOS Reminders to Org mode buffer, and it looks like `org-refile` failed without any change.
